# Generated by Django 3.2.7 on 2021-10-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20211002_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
