# Generated by Django 3.2.7 on 2021-10-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_carrito_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='info_envio',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='perfil',
            field=models.CharField(max_length=200),
        ),
    ]
