# Generated by Django 3.2.7 on 2021-10-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devoluciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entregas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enviado', models.BooleanField(default=False)),
                ('fecha_envio', models.DateField()),
                ('entregado', models.BooleanField(default=False)),
                ('fecha_entrega', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Garantias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('fecha_entrada', models.DateField(auto_now_add=True)),
                ('fecha_salida', models.DateField()),
                ('reparado', models.BooleanField(default=False)),
            ],
        ),
    ]
