# Generated by Django 3.2.7 on 2021-10-04 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20211003_1839'),
        ('Servicios', '0002_auto_20211003_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devoluciones',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.producto'),
        ),
        migrations.AlterField(
            model_name='entregas',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.carrito'),
        ),
        migrations.AlterField(
            model_name='entregas',
            name='fecha_entrega',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entregas',
            name='fecha_envio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='garantias',
            name='fecha_salida',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='garantias',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.producto'),
        ),
    ]
