# Generated by Django 3.2.7 on 2021-10-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0003_auto_20211004_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregas',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entregas',
            name='fecha_envio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
